name = "nadhebe"
compatibility_date = "2025-07-25"
compatibility_flags = ["nodejs_compat"]
main = "worker.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[ai]
binding = "AI"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1


