export interface SocialMediaPreset {
  id: string;
  platform: 'YouTube' | 'Instagram' | 'X (Twitter)' | 'LinkedIn' | 'Facebook' | 'TikTok';
  format: string;
  width: number;
  height: number;
  aspectRatio: string;
  orientation: 'Landscape' | 'Portrait' | 'Square';
  notes: string;
  safeZone?: string;
  source: string;
  sourceUrl: string;
  lastVerified: string;
  type: 'official' | 'recommended';
}

export const SOCIAL_MEDIA_PRESETS: SocialMediaPreset[] = [
  // YouTube
  {
    id: 'yt-banner',
    platform: 'YouTube',
    format: 'Channel Banner / Header',
    width: 2560,
    height: 1440,
    aspectRatio: '16:9',
    orientation: 'Landscape',
    notes: 'Safe area for text and logos on all devices is 1235 × 338 px (centered).',
    safeZone: '1235 × 338 px',
    source: 'YouTube Help Documentation',
    sourceUrl: 'https://support.google.com/youtube/answer/2660551',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'yt-thumb',
    platform: 'YouTube',
    format: 'Video Thumbnail',
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    orientation: 'Landscape',
    notes: 'Minimum width is 640 px. File size under 2MB (JPG, PNG, GIF).',
    source: 'YouTube Creator Help',
    sourceUrl: 'https://support.google.com/youtube/answer/72431',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'yt-shorts',
    platform: 'YouTube',
    format: 'YouTube Shorts Video',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    orientation: 'Portrait',
    notes: 'Vertical mobile video format. Up to 60 seconds duration.',
    source: 'YouTube Creator Help',
    sourceUrl: 'https://support.google.com/youtube/answer/10059070',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'yt-avatar',
    platform: 'YouTube',
    format: 'Channel Profile Picture',
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    orientation: 'Square',
    notes: 'Rendered as a circle in YouTube UI.',
    source: 'YouTube Creator Help',
    sourceUrl: 'https://support.google.com/youtube/answer/2972003',
    lastVerified: '2026-07-28',
    type: 'official',
  },

  // Instagram
  {
    id: 'ig-portrait',
    platform: 'Instagram',
    format: 'Portrait Feed Post',
    width: 1080,
    height: 1350,
    aspectRatio: '4:5',
    orientation: 'Portrait',
    notes: 'Takes up maximum vertical screen real estate in mobile feed.',
    source: 'Instagram Help Center',
    sourceUrl: 'https://help.instagram.com/1038071037000574',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'ig-square',
    platform: 'Instagram',
    format: 'Square Feed Post',
    width: 1080,
    height: 1080,
    aspectRatio: '1:1',
    orientation: 'Square',
    notes: 'Classic square grid post format.',
    source: 'Instagram Help Center',
    sourceUrl: 'https://help.instagram.com/1038071037000574',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'ig-reels',
    platform: 'Instagram',
    format: 'Reels & Stories Video',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    orientation: 'Portrait',
    notes: 'Keep important captions away from top header and bottom captions overlay.',
    source: 'Instagram Business Guidelines',
    sourceUrl: 'https://help.instagram.com/1038071037000574',
    lastVerified: '2026-07-28',
    type: 'official',
  },

  // X (Twitter)
  {
    id: 'x-header',
    platform: 'X (Twitter)',
    format: 'Profile Header Banner',
    width: 1500,
    height: 500,
    aspectRatio: '3:1',
    orientation: 'Landscape',
    notes: 'Profile avatar overlaps bottom-left corner of header by ~133px.',
    source: 'X Help Center',
    sourceUrl: 'https://help.twitter.com/en/managing-your-account/how-to-customize-your-profile',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'x-post',
    platform: 'X (Twitter)',
    format: 'In-Feed Image Post',
    width: 1600,
    height: 900,
    aspectRatio: '16:9',
    orientation: 'Landscape',
    notes: 'Single image post aspect ratio ideal for feed preview.',
    source: 'X Business Guidelines',
    sourceUrl: 'https://business.twitter.com/en/help/campaign-editing-and-optimization/media-specs.html',
    lastVerified: '2026-07-28',
    type: 'recommended',
  },

  // LinkedIn
  {
    id: 'li-banner',
    platform: 'LinkedIn',
    format: 'Profile Cover Banner',
    width: 1584,
    height: 396,
    aspectRatio: '4:1',
    orientation: 'Landscape',
    notes: 'Personal profile background image.',
    source: 'LinkedIn Help Center',
    sourceUrl: 'https://www.linkedin.com/help/linkedin/answer/a524794',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'li-company-banner',
    platform: 'LinkedIn',
    format: 'Company Page Cover',
    width: 1128,
    height: 191,
    aspectRatio: '5.9:1',
    orientation: 'Landscape',
    notes: 'Company brand page cover banner.',
    source: 'LinkedIn Help Center',
    sourceUrl: 'https://www.linkedin.com/help/linkedin/answer/a545596',
    lastVerified: '2026-07-28',
    type: 'official',
  },
  {
    id: 'li-post',
    platform: 'LinkedIn',
    format: 'In-Feed Image / Carousel',
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    orientation: 'Landscape',
    notes: '1:1 (1080×1080) and 4:5 (1080×1350) also supported for documents/PDF carousels.',
    source: 'LinkedIn Marketing Solutions',
    sourceUrl: 'https://www.linkedin.com/help/linkedin/answer/a545596',
    lastVerified: '2026-07-28',
    type: 'recommended',
  },

  // TikTok
  {
    id: 'tt-video',
    platform: 'TikTok',
    format: 'Vertical Video Post',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    orientation: 'Portrait',
    notes: 'Full screen vertical format. Leave right margin clear for like/share buttons.',
    source: 'TikTok Business Help Center',
    sourceUrl: 'https://ads.tiktok.com/help/article/image-ad-specifications',
    lastVerified: '2026-07-28',
    type: 'official',
  },
];
