export interface ToolRoadmapCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  audience: string;
  priority: 'Launch' | 'Growth' | 'Expansion';
  plannedCount: number;
  examples: string[];
}

export const TOOL_PLATFORM_PILLARS = [
  {
    title: 'Local-first privacy',
    description: 'Favor browser memory, Web Workers, WASM, and WebGPU so sensitive inputs stay on the user device.',
  },
  {
    title: 'AI-native utilities',
    description: 'Add MCP, prompt engineering, context-window, tokenization, agent, and workflow tools before legacy competitors do.',
  },
  {
    title: 'SEO-readable pages',
    description: 'Ship every tool and category as static HTML with schema, FAQs, related tools, and internal linking.',
  },
  {
    title: 'Composable workflows',
    description: 'Design tools so outputs can later be piped into adjacent converters, validators, generators, and analyzers.',
  },
] as const;

export const ROADMAP_CATEGORIES: ToolRoadmapCategory[] = [
  {
    id: 'developer',
    name: 'Developer',
    slug: 'developer',
    description: 'Core code formatting, conversion, diffing, linting, and generation utilities for day-to-day engineering work.',
    audience: 'Software developers and technical founders',
    priority: 'Launch',
    plannedCount: 15,
    examples: ['JSON diff', 'Base64 encoder', 'URL parser', 'JWT debugger', 'UUID generator'],
  },
  {
    id: 'ai',
    name: 'AI',
    slug: 'ai',
    description: 'Practical AI utilities for model selection, prompt diagnostics, inference planning, and local model workflows.',
    audience: 'AI engineers, prompt designers, and builders',
    priority: 'Launch',
    plannedCount: 15,
    examples: ['Prompt grader', 'Model comparison helper', 'Embedding inspector', 'AI cost estimator', 'System prompt linter'],
  },
  {
    id: 'image',
    name: 'Image',
    slug: 'image',
    description: 'Image dimensions, optimization, conversion, metadata, compression, and batch preparation tools.',
    audience: 'Designers, webmasters, marketers, and creators',
    priority: 'Launch',
    plannedCount: 13,
    examples: ['Image compressor', 'EXIF remover', 'WebP converter', 'Favicon generator', 'Background remover'],
  },
  {
    id: 'video',
    name: 'Video',
    slug: 'video',
    description: 'Video sizing, metadata, compression planning, bitrate math, aspect-ratio, and platform export helpers.',
    audience: 'YouTubers, editors, creators, and growth teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Bitrate calculator', 'Thumbnail checker', 'Shorts crop planner', 'Frame extractor', 'Subtitle converter'],
  },
  {
    id: 'audio',
    name: 'Audio',
    slug: 'audio',
    description: 'Audio conversion, waveform, loudness, podcast, transcription-prep, and production utilities.',
    audience: 'Podcasters, editors, musicians, and creators',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['LUFS calculator', 'BPM tapper', 'Waveform preview', 'Audio trimmer', 'Podcast chapter formatter'],
  },
  {
    id: 'pdf',
    name: 'PDF',
    slug: 'pdf',
    description: 'Privacy-first PDF inspection, merging, splitting, compression, extraction, and conversion helpers.',
    audience: 'Knowledge workers, students, and operations teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['PDF merge', 'PDF split', 'Page counter', 'Metadata remover', 'PDF to images'],
  },
  {
    id: 'text',
    name: 'Text',
    slug: 'text',
    description: 'Text cleanup, counting, transformation, deduplication, sorting, casing, and content preparation utilities.',
    audience: 'Writers, editors, developers, and analysts',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Word counter', 'Case converter', 'Duplicate remover', 'Slug generator', 'Text diff'],
  },
  {
    id: 'seo',
    name: 'SEO',
    slug: 'seo',
    description: 'Technical SEO, structured data, meta tags, crawlability, sitemap, robots, and SERP preview tools.',
    audience: 'SEOs, publishers, and site owners',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['SERP preview', 'Robots tester', 'Canonical checker', 'Schema validator', 'Redirect chain checker'],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    slug: 'marketing',
    description: 'Campaign planning, UTM generation, copy testing, offer math, funnel calculators, and tracking utilities.',
    audience: 'Growth marketers and founders',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['UTM builder', 'ROAS calculator', 'CAC payback', 'Headline variants', 'Campaign URL QA'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube',
    description: 'YouTube title, thumbnail, chapter, sizing, metadata, and creator workflow tools.',
    audience: 'YouTube creators and video teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Title length checker', 'Chapter formatter', 'Thumbnail safe area', 'Description template', 'Tag extractor'],
  },
  {
    id: 'social-media',
    name: 'Social Media',
    slug: 'social-media',
    description: 'Social image sizes, copy formatting, hashtag planning, profile previews, and platform-specific asset tools.',
    audience: 'Creators, marketers, and social teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['LinkedIn post preview', 'Hashtag counter', 'Bio formatter', 'Carousel size helper', 'X card preview'],
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    slug: 'prompt-engineering',
    description: 'Prompt structure, evaluation, templating, variables, guardrails, and reusable prompt asset generators.',
    audience: 'Prompt engineers and AI product teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Prompt template builder', 'Prompt variable checker', 'Eval rubric generator', 'Role prompt builder', 'Few-shot formatter'],
  },
  {
    id: 'llms',
    name: 'LLMs',
    slug: 'llms',
    description: 'Context windows, token estimates, pricing math, benchmark comparison, and model workflow calculators.',
    audience: 'LLM app developers and engineering leaders',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Token estimator', 'Context budget planner', 'Inference cost calculator', 'Chunk size planner', 'Rate limit planner'],
  },
  {
    id: 'json',
    name: 'JSON',
    slug: 'json',
    description: 'A complete JSON workbench for formatting, minifying, validating, conversion, schema, pathing, and diffing.',
    audience: 'Frontend, backend, API, and data engineers',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['JSON path finder', 'JSON schema generator', 'JSON repair', 'JSON sorter', 'JSON flatten'],
  },
  {
    id: 'xml',
    name: 'XML',
    slug: 'xml',
    description: 'XML formatting, validation, conversion, XPath, sitemap, feed, and structured document utilities.',
    audience: 'Backend developers, SEOs, and integration teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['XPath tester', 'XML validator', 'RSS checker', 'XML minifier', 'XML to CSV'],
  },
  {
    id: 'csv',
    name: 'CSV',
    slug: 'csv',
    description: 'CSV conversion, cleanup, delimiter detection, validation, sampling, and table transformation tools.',
    audience: 'Data analysts, operations teams, and developers',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['CSV validator', 'Delimiter converter', 'CSV preview', 'Column extractor', 'CSV deduper'],
  },
  {
    id: 'regex',
    name: 'Regex',
    slug: 'regex',
    description: 'Regex building, explanation, testing, escaping, extraction, replacement, and language-specific helpers.',
    audience: 'Developers, analysts, and technical operators',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Regex tester', 'Regex explainer', 'Escape helper', 'Named group checker', 'Find and replace lab'],
  },
  {
    id: 'hash',
    name: 'Hash',
    slug: 'hash',
    description: 'Hashing, checksum, HMAC, file fingerprint, password hash, and integrity verification utilities.',
    audience: 'Developers, DevOps, and security teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['SHA-256 hash', 'MD5 checksum', 'HMAC generator', 'File hash verifier', 'bcrypt checker'],
  },
  {
    id: 'security',
    name: 'Security',
    slug: 'security',
    description: 'Security helpers for encoding, encryption, headers, secrets hygiene, certificates, and safe diagnostics.',
    audience: 'Security engineers, developers, and IT teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['CSP builder', 'Password generator', 'JWT inspector', 'TLS checker', 'Secret redactor'],
  },
  {
    id: 'networking',
    name: 'Networking',
    slug: 'networking',
    description: 'DNS, IP, CIDR, HTTP, headers, ports, latency, and network planning utilities.',
    audience: 'DevOps, SREs, backend developers, and IT teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['CIDR calculator', 'DNS lookup helper', 'HTTP header parser', 'Port reference', 'IP range planner'],
  },
  {
    id: 'devops',
    name: 'DevOps',
    slug: 'devops',
    description: 'CI/CD, Docker, Kubernetes, environment, logs, config, and deployment readiness utilities.',
    audience: 'DevOps engineers, platform teams, and founders',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['Dockerfile linter', 'Cron explainer', 'Env diff', 'Kubernetes resource calculator', 'Log formatter'],
  },
  {
    id: 'cloud',
    name: 'Cloud',
    slug: 'cloud',
    description: 'Cloud cost, region, storage, bandwidth, architecture, and migration planning utilities.',
    audience: 'Cloud architects and engineering teams',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['Bandwidth cost estimator', 'S3 policy helper', 'Region latency planner', 'Instance comparer', 'Cloud egress calculator'],
  },
  {
    id: 'git',
    name: 'Git',
    slug: 'git',
    description: 'Git workflow helpers for commits, diffs, patches, branches, releases, changelogs, and repo hygiene.',
    audience: 'Developers and engineering teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Commit message builder', 'Patch viewer', 'Gitignore generator', 'Semver helper', 'Changelog formatter'],
  },
  {
    id: 'database',
    name: 'Database',
    slug: 'database',
    description: 'SQL formatting, schema design, query planning, migration, indexing, and data-model utilities.',
    audience: 'Backend developers, DBAs, and analysts',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['SQL formatter', 'Index planner', 'ERD helper', 'Migration diff', 'Query parameterizer'],
  },
  {
    id: 'finance',
    name: 'Finance',
    slug: 'finance',
    description: 'Business, pricing, ecommerce, SaaS, tax, margin, compounding, and personal finance calculators.',
    audience: 'Founders, operators, creators, and finance teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['MRR calculator', 'LTV calculator', 'Fee calculator', 'Compound interest', 'Break-even planner'],
  },
  {
    id: 'calculators',
    name: 'Calculators',
    slug: 'calculators',
    description: 'General-purpose math, percentage, geometry, ratio, unit, statistics, and practical calculators.',
    audience: 'Students, creators, and general users',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Percentage change', 'Ratio simplifier', 'Average calculator', 'Triangle solver', 'Rule of three'],
  },
  {
    id: 'unit-conversion',
    name: 'Unit Conversion',
    slug: 'unit-conversion',
    description: 'Unit converters for distance, weight, volume, speed, area, temperature, energy, and engineering dimensions.',
    audience: 'Students, engineers, makers, and general users',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Length converter', 'Temperature converter', 'Area converter', 'Speed converter', 'Energy converter'],
  },
  {
    id: 'date-time',
    name: 'Date & Time',
    slug: 'date-time',
    description: 'Date math, timezone, Unix timestamp, duration, scheduling, countdown, and calendar utilities.',
    audience: 'Developers, operators, and distributed teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Unix timestamp converter', 'Timezone planner', 'Date difference', 'Cron next-run viewer', 'ISO date formatter'],
  },
  {
    id: 'color',
    name: 'Color',
    slug: 'color',
    description: 'Color conversion, contrast, palette, gradient, accessibility, and design-token generation utilities.',
    audience: 'Designers, frontend developers, and brand teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['HEX to RGB', 'Palette generator', 'Gradient builder', 'Contrast checker', 'Color blindness simulator'],
  },
  {
    id: 'design',
    name: 'Design',
    slug: 'design',
    description: 'Layout, spacing, sizing, grids, icon, export, mockup, and asset-preparation utilities.',
    audience: 'Product designers and frontend teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Grid calculator', 'Spacing scale generator', 'Icon resizer', 'Safe area helper', 'Design token mapper'],
  },
  {
    id: 'typography',
    name: 'Typography',
    slug: 'typography',
    description: 'Type scale, clamp, line-height, readability, font pairing, and CSS typography tools.',
    audience: 'Designers, developers, and publishers',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Type scale generator', 'Line-height calculator', 'Fluid type builder', 'Readability checker', 'Font fallback stack'],
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    slug: 'accessibility',
    description: 'Accessibility testing, WCAG contrast, ARIA, keyboard, alt text, and inclusive design helpers.',
    audience: 'Frontend teams, designers, and QA teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['ARIA role helper', 'Alt text checker', 'Focus order planner', 'Contrast matrix', 'Tap target checker'],
  },
  {
    id: 'browser',
    name: 'Browser',
    slug: 'browser',
    description: 'Browser compatibility, storage, feature detection, headers, viewport, cookies, and web platform utilities.',
    audience: 'Frontend developers and QA teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['User-agent parser', 'Viewport tester', 'Cookie decoder', 'LocalStorage inspector', 'Feature support checker'],
  },
  {
    id: 'performance',
    name: 'Performance',
    slug: 'performance',
    description: 'Performance budgets, Core Web Vitals, image weight, bundle size, latency, and optimization planning tools.',
    audience: 'Frontend engineers, SEOs, and performance teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Performance budget planner', 'LCP image estimator', 'Bundle size calculator', 'CLS checklist', 'Latency simulator'],
  },
  {
    id: 'productivity',
    name: 'Productivity',
    slug: 'productivity',
    description: 'Personal workflow utilities for checklists, planning, conversion, notes, templates, and repetitive operations.',
    audience: 'Knowledge workers and operators',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['Checklist builder', 'Decision matrix', 'Pomodoro planner', 'Meeting notes formatter', 'CSV task importer'],
  },
  {
    id: 'writing',
    name: 'Writing',
    slug: 'writing',
    description: 'Writing utilities for clarity, structure, headlines, outlines, reading time, tone, and publishing prep.',
    audience: 'Writers, editors, marketers, and students',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Reading time calculator', 'Headline analyzer', 'Outline builder', 'Tone checker', 'Summary length planner'],
  },
  {
    id: 'education',
    name: 'Education',
    slug: 'education',
    description: 'Study, grading, citation, flashcard, quiz, formula, and learning-support utilities.',
    audience: 'Students, teachers, and independent learners',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['GPA calculator', 'Flashcard generator', 'Citation formatter', 'Quiz builder', 'Study schedule planner'],
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis',
    slug: 'data-analysis',
    description: 'Data cleaning, profiling, statistics, sampling, table inspection, and lightweight analysis utilities.',
    audience: 'Analysts, operators, researchers, and developers',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['Column profiler', 'Outlier detector', 'Sample size calculator', 'Correlation helper', 'Data type detector'],
  },
  {
    id: 'visualization',
    name: 'Visualization',
    slug: 'visualization',
    description: 'Chart generation, diagram helpers, color scales, SVG utilities, and visual data exploration tools.',
    audience: 'Analysts, publishers, and product teams',
    priority: 'Expansion',
    plannedCount: 12,
    examples: ['Chart chooser', 'Mermaid preview', 'Color scale generator', 'SVG chart builder', 'Sparkline generator'],
  },
  {
    id: 'api',
    name: 'API',
    slug: 'api',
    description: 'API design, OpenAPI, webhooks, payload validation, response formatting, and integration helpers.',
    audience: 'API developers and integration teams',
    priority: 'Growth',
    plannedCount: 12,
    examples: ['OpenAPI starter', 'Webhook tester', 'cURL builder', 'HTTP status reference', 'API error formatter'],
  },
  {
    id: 'mcp',
    name: 'MCP',
    slug: 'mcp',
    description: 'Model Context Protocol utilities for server scaffolding, manifest generation, tool schema design, and debugging.',
    audience: 'AI app developers and agent-tool builders',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['MCP manifest builder', 'Tool schema generator', 'Resource template planner', 'Server checklist', 'Claude connector helper'],
  },
  {
    id: 'automation-agents',
    name: 'Automation & Agents',
    slug: 'automation-agents',
    description: 'Agent workflow, n8n, Zapier, ComfyUI, task graph, handoff, and automation planning utilities.',
    audience: 'Automation builders, AI operators, and growth teams',
    priority: 'Launch',
    plannedCount: 12,
    examples: ['Agent task graph builder', 'n8n workflow planner', 'Zapier formatter', 'ComfyUI prompt helper', 'Handoff checklist'],
  },
];

export const ROADMAP_TOTAL_TOOLS = ROADMAP_CATEGORIES.reduce((total, category) => total + category.plannedCount, 0);

export function getRoadmapCategoryBySlug(slug: string): ToolRoadmapCategory | undefined {
  return ROADMAP_CATEGORIES.find((category) => category.slug === slug || category.id === slug);
}
